/**
 * Docker Compose YAML generator.
 *
 * Given a configuration object, produces a valid docker-compose.yml string
 * and a corresponding .env file for the MCP Context Manager + UI services.
 */

export interface DockerConfig {
  workspaceRoot: string;
  httpPort: number;
  uiPort: number;
  watchedDirs: string[];
  memoryLimit: string;
  logLevel: string;
  volumes: VolumeMapping[];
}

export interface VolumeMapping {
  source: string;
  readOnly: boolean;
}

export const DEFAULT_CONFIG: DockerConfig = {
  workspaceRoot: "./",
  httpPort: 3001,
  uiPort: 8080,
  watchedDirs: ["backend/", "frontend/src/", "services/"],
  memoryLimit: "512M",
  logLevel: "info",
  volumes: [
    { source: "backend", readOnly: true },
    { source: "frontend", readOnly: true },
    { source: "services", readOnly: true },
  ],
};

/**
 * Generate docker-compose.yml content from configuration.
 */
export function generateDockerCompose(config: DockerConfig): string {
  const volumeMappings = config.volumes
    .map((v) => {
      const ro = v.readOnly ? ":ro" : "";
      return `      - ./${v.source}:/workspace/${v.source}${ro}`;
    })
    .join("\n");

  return `# MCP Context Manager — Docker Compose Configuration
# Generated by MCP Context UI Setup Wizard

services:
  # ─── MCP Context Manager ──────────────────────────────────────────────
  # Model Context Protocol service for live codebase analysis
  mcp-context-manager:
    build:
      context: .
      dockerfile: services/mcp-context-manager/Dockerfile
    container_name: mcp-context-manager
    environment:
      - WORKSPACE_ROOT=/workspace
      - HTTP_PORT=${config.httpPort}
      - LOG_LEVEL=${config.logLevel}
    volumes:
${volumeMappings}
    expose:
      - "${config.httpPort}"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${config.memoryLimit}
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:${config.httpPort}/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # ─── MCP Context UI ───────────────────────────────────────────────────
  # Documentation portal and graph visualization
  mcp-ui:
    build:
      context: ./services/mcp-context-ui
      dockerfile: Dockerfile
    container_name: mcp-context-ui
    ports:
      - "${config.uiPort}:80"
    depends_on:
      mcp-context-manager:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://127.0.0.1:80/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
`;
}

/**
 * Generate .env file content from configuration.
 */
export function generateEnvFile(config: DockerConfig): string {
  return `# MCP Context Manager — Environment Configuration
# Generated by MCP Context UI Setup Wizard

WORKSPACE_ROOT=${config.workspaceRoot}
HTTP_PORT=${config.httpPort}
UI_PORT=${config.uiPort}
LOG_LEVEL=${config.logLevel}
MEMORY_LIMIT=${config.memoryLimit}
`;
}

/**
 * Generate run commands for quick start.
 */
export function generateRunCommands(config: DockerConfig): string {
  return `# Build and start MCP services
docker-compose up -d mcp-context-manager mcp-ui

# Verify services are running
docker-compose ps

# Check MCP Context Manager health
curl http://localhost:${config.httpPort}/api/v1/health

# View MCP Context Manager logs
docker-compose logs -f mcp-context-manager

# Open the UI
open http://localhost:${config.uiPort}

# Stop services
docker-compose down
`;
}
